services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Bit-els
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    container_name: backend
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./Frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
